# This is a basic workflow to help you get started with Actions

name: lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
     - name: GolangCI-Linter
       uses: Mushus/golangci-linter@v1.1.2

